Derp.onclick = () => {headText3.textContent = descriptionCheatsArr[0]}
SkinDerp.onclick = () => {headText3.textContent = descriptionCheatsArr[1]}
AutoBreak.onclick = () => {headText3.textContent = descriptionCheatsArr[2]}
ChestAura.onclick = () => {headText3.textContent = descriptionCheatsArr[4]}
ChestStealer.onclick = () => {headText3.textContent = descriptionCheatsArr[4]}
CivBreak.onclick = () => {headText3.textContent = descriptionCheatsArr[5]}
FastBreak.onclick = () => {headText3.textContent = descriptionCheatsArr[6]}
FastPlace.onclick = () => {headText3.textContent = descriptionCheatsArr[7]}
Fucker.onclick = () => {headText3.textContent = descriptionCheatsArr[8]}
Luquids.onclick = () => {headText3.textContent = descriptionCheatsArr[9]}
NoSlowBreak.onclick = () => {headText3.textContent = descriptionCheatsArr[10]}
Nuker.onclick = () => {headText3.textContent = descriptionCheatsArr[11]}
Scaffold.onclick = () => {headText3.textContent = descriptionCheatsArr[12]}
Timer.onclick = () => {headText3.textContent = descriptionCheatsArr[13]}
Tower.onclick = () => {headText3.textContent = descriptionCheatsArr[14]}
Players.onclick = () => {headText3.textContent = descriptionCheatsArr[15]}
Mobs.onclick = () => {headText3.textContent = descriptionCheatsArr[16]}
Animals.onclick = () => {headText3.textContent = descriptionCheatsArr[17]}
Invisible.onclick = () => {headText3.textContent = descriptionCheatsArr[18]}
Dead.onclick = () => {headText3.textContent = descriptionCheatsArr[19]}
AntiBot.onclick = () => {headText3.textContent = descriptionCheatsArr[20]}
AtAllProvider.onclick = () => {headText3.textContent = descriptionCheatsArr[21]}
ComponentOnHover.onclick = () => {headText3.textContent = descriptionCheatsArr[22]}
LiquidChat.onclick = () => {headText3.textContent = descriptionCheatsArr[23]}
MidClick.onclick = () => {headText3.textContent = descriptionCheatsArr[24]}
NameProtect.onclick = () => {headText3.textContent = descriptionCheatsArr[25]}
NoRotatetSet.onclick = () => {headText3.textContent = descriptionCheatsArr[26]}
ResoursePackSpoof.onclick = () => {headText3.textContent = descriptionCheatsArr[27]}
Spammmer.onclick = () => {headText3.textContent = descriptionCheatsArr[28]}
Teams.onclick = () => {headText3.textContent = descriptionCheatsArr[29]}
AntiAFK.onclick = () => {headText3.textContent = descriptionCheatsArr[30]}
AntiCactus.onclick = () => {headText3.textContent = descriptionCheatsArr[31]}
AutoRespawn.onclick = () => {headText3.textContent = descriptionCheatsArr[32]}
AutoTool.onclick = () => {headText3.textContent = descriptionCheatsArr[33]}
Blink.onclick = () => {headText3.textContent = descriptionCheatsArr[34]}
Eagle.onclick = () => {headText3.textContent = descriptionCheatsArr[35]}
FastUse.onclick = () => {headText3.textContent = descriptionCheatsArr[36]}
InventoryCleaner.onclick = () => {headText3.textContent = descriptionCheatsArr[37]}
KeepAlive.onclick = () => {headText3.textContent = descriptionCheatsArr[38]}
NoFall.onclick = () => {headText3.textContent = descriptionCheatsArr[39]}
Reach.onclick = () => {headText3.textContent = descriptionCheatsArr[40]}
Regen.onclick = () => {headText3.textContent = descriptionCheatsArr[41]}
Zoot.onclick = () => {headText3.textContent = descriptionCheatsArr[42]}
AirJump.onclick = () => {headText3.textContent = descriptionCheatsArr[43]}
AirLadder.onclick = () => {headText3.textContent = descriptionCheatsArr[44]}
AutoWalk.onclick = () => {headText3.textContent = descriptionCheatsArr[45]}
BlockWalk.onclick = () => {headText3.textContent = descriptionCheatsArr[46]}
BufferSpeed.onclick = () => {headText3.textContent = descriptionCheatsArr[47]}
BugUp.onclick = () => {headText3.textContent = descriptionCheatsArr[48]}
FastClimb.onclick = () => {headText3.textContent = descriptionCheatsArr[49]}
FastStairs.onclick = () => {headText3.textContent = descriptionCheatsArr[50]}
Fly.onclick = () => {headText3.textContent = descriptionCheatsArr[51]}
Freeze.onclick = () => {headText3.textContent = descriptionCheatsArr[52]}
HighJump.onclick = () => {headText3.textContent = descriptionCheatsArr[53]}
IceSpeed.onclick = () => {headText3.textContent = descriptionCheatsArr[54]}
InventoryMove.onclick = () => {headText3.textContent = descriptionCheatsArr[55]}
LadderJump.onclick = () => {headText3.textContent = descriptionCheatsArr[56]}
LiquidWalk.onclick = () => {headText3.textContent = descriptionCheatsArr[57]}
LongJump.onclick = () => {headText3.textContent = descriptionCheatsArr[58]}
NoClip.onclick = () => {headText3.textContent = descriptionCheatsArr[59]}
NoJumpDelay.onclick = () => {headText3.textContent = descriptionCheatsArr[60]}
NoSlow.onclick = () => {headText3.textContent = descriptionCheatsArr[61]}
NoWeb.onclick = () => {headText3.textContent = descriptionCheatsArr[62]}
Parkour.onclick = () => {headText3.textContent = descriptionCheatsArr[63]}
PerfectHorseJump.onclick = () => {headText3.textContent = descriptionCheatsArr[64]}
ReverseStep.onclick = () => {headText3.textContent = descriptionCheatsArr[65]}
SafeWalk.onclick = () => {headText3.textContent = descriptionCheatsArr[66]}
SlimeJump.onclick = () => {headText3.textContent = descriptionCheatsArr[67]}
Sneak.onclick = () => {headText3.textContent = descriptionCheatsArr[68]}
Speed.onclick = () => {headText3.textContent = descriptionCheatsArr[69]}
Step.onclick = () => {headText3.textContent = descriptionCheatsArr[70]}
Strafe.onclick = () => {headText3.textContent = descriptionCheatsArr[71]}
WallClimb.onclick = () => {headText3.textContent = descriptionCheatsArr[72]}
WaterSpeed.onclick = () => {headText3.textContent = descriptionCheatsArr[73]}
AntiBlind.onclick = () => {headText3.textContent = descriptionCheatsArr[74]}
BlockESP.onclick = () => {headText3.textContent = descriptionCheatsArr[75]}
BlockOverlay.onclick = () => {headText3.textContent = descriptionCheatsArr[76]}
BreadCrumbs.onclick = () => {headText3.textContent = descriptionCheatsArr[77]}
CameraClip.onclick = () => {headText3.textContent = descriptionCheatsArr[78]}
Chams.onclick = () => {headText3.textContent = descriptionCheatsArr[79]}
ClickGUI.onclick = () => {headText3.textContent = descriptionCheatsArr[80]}
ESP.onclick = () => {headText3.textContent = descriptionCheatsArr[81]}
FreeCam.onclick = () => {headText3.textContent = descriptionCheatsArr[82]}
FullBright.onclick = () => {headText3.textContent = descriptionCheatsArr[83]}
HUD.onclick = () => {headText3.textContent = descriptionCheatsArr[84]}
ItemESP.onclick = () => {headText3.textContent = descriptionCheatsArr[85]}
NameTags.onclick = () => {headText3.textContent = descriptionCheatsArr[86]}
NoBob.onclick = () => {headText3.textContent = descriptionCheatsArr[87]}
NoFOV.onclick = () => {headText3.textContent = descriptionCheatsArr[88]}
NoHurtCam.onclick = () => {headText3.textContent = descriptionCheatsArr[89]}
NoScoreboard.onclick = () => {headText3.textContent = descriptionCheatsArr[90]}
NoSwing.onclick = () => {headText3.textContent = descriptionCheatsArr[91]}
Projectiles.onclick = () => {headText3.textContent = descriptionCheatsArr[92]}
ProphuntESP.onclick = () => {headText3.textContent = descriptionCheatsArr[93]}
Rotations.onclick = () => {headText3.textContent = descriptionCheatsArr[94]}
StorageESP.onclick = () => {headText3.textContent = descriptionCheatsArr[95]}
TNTESP.onclick = () => {headText3.textContent = descriptionCheatsArr[96]}
Tracers.onclick = () => {headText3.textContent = descriptionCheatsArr[97]}
TrueSight.onclick = () => {headText3.textContent = descriptionCheatsArr[98]}
XRay.onclick = () => {headText3.textContent = descriptionCheatsArr[99]}
AbortBreaking.onclick = () => {headText3.textContent = descriptionCheatsArr[100]}
AntiHunger.onclick = () => {headText3.textContent = descriptionCheatsArr[101]}
BedGodMode.onclick = () => {headText3.textContent = descriptionCheatsArr[102]}
Clip.onclick = () => {headText3.textContent = descriptionCheatsArr[103]}
ConsoleSpammer.onclick = () => {headText3.textContent = descriptionCheatsArr[104]}
Damage.onclick = () => {headText3.textContent = descriptionCheatsArr[105]}
ForceUnicodeChat.onclick = () => {headText3.textContent = descriptionCheatsArr[106]}
Ghost.onclick = () => {headText3.textContent = descriptionCheatsArr[107]}
GhostHand.onclick = () => {headText3.textContent = descriptionCheatsArr[108]}
GodMode.onclick = () => {headText3.textContent = descriptionCheatsArr[109]}
ItemTeleport.onclick = () => {headText3.textContent = descriptionCheatsArr[110]}
KeepContainer.onclick = () => {headText3.textContent = descriptionCheatsArr[111]}
Kick.onclick = () => {headText3.textContent = descriptionCheatsArr[112]}
MoreCarry.onclick = () => {headText3.textContent = descriptionCheatsArr[113]}
MultiActions.onclick = () => {headText3.textContent = descriptionCheatsArr[114]}
NoPitchLimit.onclick = () => {headText3.textContent = descriptionCheatsArr[115]}
Phase.onclick = () => {headText3.textContent = descriptionCheatsArr[116]}
Plugins.onclick = () => {headText3.textContent = descriptionCheatsArr[117]}
PortalMenu.onclick = () => {headText3.textContent = descriptionCheatsArr[118]}
ServerCrasher.onclick = () => {headText3.textContent = descriptionCheatsArr[119]}
Teleport.onclick = () => {headText3.textContent = descriptionCheatsArr[120]}
AimBot.onclick = () => {headText3.textContent = descriptionCheatsArr[121]}
AutoArmor.onclick = () => {headText3.textContent = descriptionCheatsArr[122]}
AutoBow.onclick = () => {headText3.textContent = descriptionCheatsArr[123]}
AutoClicker.onclick = () => {headText3.textContent = descriptionCheatsArr[124]}
AutoLeave.onclick = () => {headText3.textContent = descriptionCheatsArr[125]}
AutoPot.onclick = () => {headText3.textContent = descriptionCheatsArr[126]}
AutoSoup.onclick = () => {headText3.textContent = descriptionCheatsArr[127]}
AutoWeapon.onclick = () => {headText3.textContent = descriptionCheatsArr[128]}
BowAimBot.onclick = () => {headText3.textContent = descriptionCheatsArr[129]}
Criticals.onclick = () => {headText3.textContent = descriptionCheatsArr[130]}
FastBow.onclick = () => {headText3.textContent = descriptionCheatsArr[131]}
HitBox.onclick = () => {headText3.textContent = descriptionCheatsArr[132]}
Ignite.onclick = () => {headText3.textContent = descriptionCheatsArr[133]}
KillAura.onclick = () => {headText3.textContent = descriptionCheatsArr[134]}
NoFriends.onclick = () => {headText3.textContent = descriptionCheatsArr[135]}
SuperKnockBack.onclick = () => {headText3.textContent = descriptionCheatsArr[136]}
TNTBlock.onclick = () => {headText3.textContent = descriptionCheatsArr[137]}
TeleportHit.onclick = () => {headText3.textContent = descriptionCheatsArr[138]}
Trigger.onclick = () => {headText3.textContent = descriptionCheatsArr[139]}
Velocity.onclick = () => {headText3.textContent = descriptionCheatsArr[140]}
Sprint.onclick = () => {headText3.textContent = descriptionCheatsArr[141]}